### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by CurryYuan** [daveredrum/Scan2Cap#1]
Your work is very interesting. Do you have a schedule about code releasing?

**Comment by daveredrum** [comment]
@CurryYuan Thx for your interest in our project! We'll release the code once we finish cleaning the codebase. Stay tuned :)

**Comment by liujiaheng** [comment]
This is very nice work, when will the code will be released? @daveredrum

**Comment by nanguoshun** [comment]
Hi Dave, nice work! May I know when you are going to release the code @daveredrum
