### ISSUE TITLE
How to visualisze it?

### ISSUE THREAD

**Issue by sijiua** [daveredrum/Scan2Cap#10]
![ce0e8e6c95365cfb969b3d88b22a90e](https://user-images.githubusercontent.com/89134118/132441397-355e61d6-7295-4da3-93ca-c3e799ad4d58.png)
why the description can not display on the 3D object and why the file.json cannot open at 3Dpicture? could u recommend me a software to open it?
![af90228d2497878da6e794ddac3c4a3](https://user-images.githubusercontent.com/89134118/132442135-498a7507-9c68-4880-a96a-50e5b7270841.png)

**Comment by daveredrum** [comment]
Hi @sijiua, 1) the descriptions won't be shown directly on the 3D object, but you can match them with the generated mesh files via the object IDs and object names; 2) `.json` files can be opened in any text editor.

**Comment by sijiua** [comment]
Thanks for your reply.
