### ISSUE TITLE
Benchmark Challenge

### ISSUE THREAD

**Issue by yvfengZhong** [daveredrum/Scan2Cap#20]
Hi, I'm really interested in the Scan2Cap Dense Captioning Benchmark, but I have some problems.

I try to run the following command.
`python benchmark/predict.py --folder <output_folder> --use_multiview --use_normal --use_topdown --use_relation --num_graph_steps 2 --num_locals 10`

Then, it encountered an error.

<img width="1116" alt="截屏2022-09-05 18 25 47" src="https://user-images.githubusercontent.com/68994274/188431095-30258b06-dfcd-44e0-a35a-b833fc63ceb2.png">

I guess the reason for this error is that the ScanNet dataset does not provide point cloud data for scene 707 to scene 806.

The file structure of the original ScanNet dataset I downloaded is shown below.

<img width="410" alt="截屏2022-09-05 18 35 57" src="https://user-images.githubusercontent.com/68994274/188431213-a1b83596-1641-4774-bd74-1bae5b7eb943.png">

Is the ScanNet dataset I downloaded missing? Or is there something wrong with the code?

**Comment by daveredrum** [comment]
Hi @yvfengZhong, thank you for your interest in our work. Did you preprocess the ScanNet data as README instructed?

**Comment by yvfengZhong** [comment]
Yes, I have preprocessed the ScanNet data and generated the folder `data/scannet/scannet_data/` after running the following command. 

`cd data/scannet/ & python batch_load_scannet_data.py
`

To preprocess the data from scene_707 to scene_806, I modified the file `data/scannet/batch_load_scannet_data.py`, as shown below. I replaced `scannetv2_train.txt` with `scannetv2_test.txt`.

<img width="675" alt="截屏2022-09-05 21 10 22" src="https://user-images.githubusercontent.com/68994274/188457329-2e30a8ad-77ae-4db6-a3f8-2a32cc029bca.png">

Now, I get the file structure of the folder `data/scannet/scannet_data` as shown below.
<img width="334" alt="截屏2022-09-05 21 22 27" src="https://user-images.githubusercontent.com/68994274/188459673-5f210704-b7a0-499b-879f-3a96332cd1ca.png">

However, I have encountered a new problem.

<img width="821" alt="截屏2022-09-05 21 14 48" src="https://user-images.githubusercontent.com/68994274/188458328-a07dbbde-bff3-4d4f-8b74-e647307b1530.png">

The `x in instance_bboxes[:num_bbox, -2]` is 0, but there are no 0 in `DC.nyu40id2class`.

So, I add an extra 0 to `DC.nyu40id2class`, as shown in the following figure.

<img width="974" alt="截屏2022-09-05 21 19 14" src="https://user-images.githubusercontent.com/68994274/188459064-d704b365-0b5d-481c-a3f3-08ab4db52d62.png">

Now, I can successfully generate the result file `pred.json`, but I don't know if my operation is correct?

**Comment by daveredrum** [comment]
It looks safe to use "others" as placeholders of the non-existing labels. Could you probably benchmark the performance first on the train split, just to make sure the predictions are reasonable?

**Comment by yvfengZhong** [comment]
The non-existing labels "0" is only in test split. 
The "\*.aggregation.json" and "\*_vh_clean_2.0.010000.segs.json" are not in the folder `data/scannet/scans_test`, so `data/scannet/load_scannet_data.py` use "0" as placeholders for the test scene.

<img width="690" alt="截屏2022-09-05 21 36 56" src="https://user-images.githubusercontent.com/68994274/188462355-174a5e06-38b4-4e36-a1fc-89d038114bab.png">

If I benchmark the performance on the train or val split by running the following command, everything is ok.

`python benchmark/predict.py --folder <output_folder> --use_multiview --use_normal --use_topdown --use_relation --num_graph_steps 2 --num_locals 10 --test_split val`

**Comment by daveredrum** [comment]
That looks good. If the results look good when you benchmark it locally on train/val split, I guess the issue is resolved then. Could you probably open a pull request, so that I can adapt the change?

**Comment by yvfengZhong** [comment]
OK, I am adjusting my model now, and I will open a pull request after sufficient verification to ensure that there is no error.

**Comment by daveredrum** [comment]
Thanks a lot for the efforts! As I wrote this code a bit more than two years ago, there might be some obsolete snippets that are beyond maintenance. Therefore, I also refer you to the new implementation of Scan2Cap [faster-captioning](https://github.com/daveredrum/faster-captioning), for that it's cleaner and faster. I hope the new repo could be helpful.

**Comment by yvfengZhong** [comment]
I have a new problem after running the following command.

`python benchmark/eval.py --split val --path <path to predictions> --verbose
`

<img width="960" alt="截屏2022-09-06 16 42 35" src="https://user-images.githubusercontent.com/68994274/188589876-791d3b4d-e82a-44b4-bf1c-0f22b9f94f2a.png">

Can you give me some suggestions?

**Comment by daveredrum** [comment]
It seems to be an issue with the `benchmark/box_util.py`. Could you give it a try now?

**Comment by yvfengZhong** [comment]
Thanks! It helps a lot!
