### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cuiheng1234** [daveredrum/Scan2Cap#8]
where is the 'votenet_{}_predictions'?

**Comment by daveredrum** [comment]
Hi @cuiheng1234, `votenet_{}_predictions` is the extracted predictions of a pre-trained VoteNet. You can for sure comment out that line in `visualize.py`

**Comment by cuiheng1234** [comment]
I have some trouble in the visualization process.What does 'axis_aligned_scene.ply' mean in visualize.py?where is it

**Comment by daveredrum** [comment]
Those are the axis-aligned ScanNet scenes - I'll add the script into the codebase a bit later. The idea is simple tho: use the `axisAlignment`matrix in the ScanNet meta file for every scan, e.g. `scene0000_00.txt`, to align the vertices of the ScanNet mesh, then store the aligned meshes.

**Comment by cuiheng1234** [comment]
Thanks

**Comment by cuiheng1234** [comment]
Hello, when will you add relevant scripts to the codebase? Thank you.
![image](https://user-images.githubusercontent.com/80439094/132306382-cee4d29c-f85f-4c4e-8705-32f399f79820.png)

**Comment by daveredrum** [comment]
Hi, those requested scripts have been added to the repo by [this commit](https://github.com/daveredrum/Scan2Cap/commit/4010475541b0af1a4af354cc2adf86a2a47cb9ee)

**Comment by cuiheng1234** [comment]
Thank you very much.
