### ISSUE TITLE
Training time suddenly becomes longer.

### ISSUE THREAD

**Issue by yvfengZhong** [daveredrum/Scan2Cap#9]
Thank you very much for your work. I have encountered some problems here.

In the first 19 epochs, the `mean_ iter_time` is kept at about 2 seconds. 
<img width="818" alt="屏幕快照 2021-09-06 上午10 51 42" src="https://user-images.githubusercontent.com/68994274/132154005-cb9976a6-d20b-4395-9e39-a2c1530e1443.png">

But in the 20th epoch, the `mean_ iter_time` suddenly became about a minute. 
<img width="817" alt="屏幕快照 2021-09-06 上午10 52 25" src="https://user-images.githubusercontent.com/68994274/132154006-3c760eb8-8a20-483f-b536-06b3c8ddd39c.png">

It puzzles me.

I have read another related answer about [Training time too long](https://github.com/daveredrum/Scan2Cap/issues/4), but I don't know why there will be such a big change after the 20th epoch.

I look forward to your answer and wish you success in your work.

**Comment by daveredrum** [comment]
Hi @yvfengZhong, can you share some info about your hardware?

**Comment by yvfengZhong** [comment]
I ran the training command `CUDA_VISIBLE_DEVICES=0 python scripts/train.py --use_multiview --use_normal --use_topdown --use_relation --use_orientation --num_graph_steps 2 --num_locals 10 --batch_size 8 --epoch 50` on the GeForce RTX 3090Ti GPU with 24GB of memory.

**Comment by daveredrum** [comment]
It seems your GPU is clogged by other process. Are you sharing your 3090Ti with others? If not, you can probably try a bigger batch size to fill your GPU.

**Comment by yvfengZhong** [comment]
Yes, I shared 3090ti with my colleagues. Now the problem has been solved. Thank you for your help!
